package org.github.ypiel.jbudget.model;

public enum EntryCategory {
    ALL,
    ACTIVITY,
    ADOPTION,
    AMAZON,
    BANK_FEES,
    CARE_HEALTH,
    CLOTHING,
    CULTURE,
    EXTRA,
    FAMILY,
    GIFTS,
    GROCERIES_HOUSEHOLD,
    HEALTH_CARE,
    HOME_IMPROVEMENT,
    HOME_LOAN,
    HOUSE_WORK,
    INCOME,
    INVESTMENT_PESO,
    LUNCH_RESTAURANT,
    NIJAT,
    OUTINGS_FRIENDS_RESTAURANT,
    PAPA,
    REMBOURSEMENT_POUR_CAROLE,
    SHARED,
    SNACK_BAKERY,
    SPORT,
    SUBSCRIPTION,
    TAXES_FEES_FINES,
    TRANSPORT,
    TRAVEL,
    UNDEFINED,
    WITHDRAWAL,
    WORK_FOOD,
}
